### ISSUE TITLE
Build BI From Scratch: problems in step 2-3 and step 3-3

### ISSUE THREAD

**Issue by radleap** [aws-samples/aws-analytics-immersion-day#1]
When running this tutorial in this workshop:

https://catalog.us-east-1.prod.workshops.aws/workshops/a861fb26-12b0-4669-b3c3-ae1def49735d/en-US

(1) in Step 2-3: the resources/online_retail.csv is not in the directory /home/ec2-user but within a subdirectory after unpacking the main.zip.

https://catalog.us-east-1.prod.workshops.aws/workshops/a861fb26-12b0-4669-b3c3-ae1def49735d/en-US/lab-setup/ec2-user-configuration

(2) Step 3-3: when running this step (after adding online_retail.csv to /home/ec2-user), getting below key error. 

https://catalog.us-east-1.prod.workshops.aws/workshops/a861fb26-12b0-4669-b3c3-ae1def49735d/en-US/build-analytics-system/verify

python3 gen_kinesis_data.py -I resources/online_retail.csv \
 --region-name us-west-2 \
 --service-name kinesis \
 --out-format json \
 --stream-name retail-trans

ERROR: 

Traceback (most recent call last):
  File "gen_kinesis_data.py", line 58, in gen_records
    data = json.dumps(OrderedDict([(k.replace(' ', '_'), SCHEMA_CONV_TOOL[k](v)) for k, v in row.items()]), ensure_ascii=False)
  File "gen_kinesis_data.py", line 58, in <listcomp>
    data = json.dumps(OrderedDict([(k.replace(' ', '_'), SCHEMA_CONV_TOOL[k](v)) for k, v in row.items()]), ensure_ascii=False)
KeyError: 'Customer ID'

**Comment by ksmin23** [comment]
Thanks for reporting error.
I fixed the runtime error of gen_kinesis_data.py, and the sample data location.
